/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dal.DocGiaDAO;
import dal.MuonTraDAO;
import dal.NhanVienDAO;
import java.awt.Color;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author hiep.tt166077
 */
public class GUIThongKeMT extends javax.swing.JFrame {

    /**
     * Creates new form GUIThongKeMT
     */
    int xx;
    int xy;
    int clickedButt = 0;
    short ngay = 1;
    
    public GUIThongKeMT() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void setLblColor(JLabel lbl) {
        lbl.setBackground(new Color(0, 150, 62));
    }

    public void resetLblColor(JLabel lbl) {
        lbl.setBackground(new Color(1, 198, 83));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTK = new javax.swing.JTable();
        btn_dm = new javax.swing.JLabel();
        btn_dg = new javax.swing.JLabel();
        btn_nv = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSlS = new javax.swing.JLabel();
        btn_ms = new javax.swing.JLabel();
        btn_tc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(1, 198, 83));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tableTK.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tableTK.setForeground(new java.awt.Color(51, 51, 51));
        tableTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableTK.setGridColor(new java.awt.Color(255, 255, 255));
        tableTK.setRowHeight(20);
        tableTK.setSelectionBackground(new java.awt.Color(1, 198, 83));
        jScrollPane1.setViewportView(tableTK);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 430, 360));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 159, 860, 370));

        btn_dm.setBackground(new java.awt.Color(1, 198, 83));
        btn_dm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_dm.setForeground(new java.awt.Color(255, 255, 255));
        btn_dm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_dm.setText("đơn mượn");
        btn_dm.setToolTipText("sô lượng đơn mượn trong ... ngày gần đây");
        btn_dm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dm.setOpaque(true);
        btn_dm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dmMouseClicked(evt);
            }
        });
        jPanel3.add(btn_dm, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 130, 30));

        btn_dg.setBackground(new java.awt.Color(1, 198, 83));
        btn_dg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_dg.setForeground(new java.awt.Color(255, 255, 255));
        btn_dg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_dg.setText("độc giả");
        btn_dg.setToolTipText("số lượng đơn mượn theo độc giả");
        btn_dg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dg.setOpaque(true);
        btn_dg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dgMouseClicked(evt);
            }
        });
        jPanel3.add(btn_dg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 30));

        btn_nv.setBackground(new java.awt.Color(1, 198, 83));
        btn_nv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_nv.setForeground(new java.awt.Color(255, 255, 255));
        btn_nv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_nv.setText("nhân viên");
        btn_nv.setToolTipText("số lượng đơn lập theo nhân viên");
        btn_nv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_nv.setOpaque(true);
        btn_nv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nvMouseClicked(evt);
            }
        });
        jPanel3.add(btn_nv, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 130, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thống kê mượn trả");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 330, -1));

        jLabel3.setBackground(new java.awt.Color(1, 198, 83));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Multiply_30px.png"))); // NOI18N
        jLabel3.setToolTipText("đóng chương trình");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 30, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Print_30px.png"))); // NOI18N
        jLabel4.setToolTipText("lưu/ in báo cáo");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons8_Reply_Arrow_30px_1.png"))); // NOI18N
        jLabel5.setToolTipText("quay lại");
        jLabel5.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtSN.setBackground(new java.awt.Color(1, 198, 83));
        txtSN.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtSN.setForeground(new java.awt.Color(255, 255, 255));
        txtSN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSNActionPerformed(evt);
            }
        });
        jPanel3.add(txtSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 30, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("ngày gần nhất");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Trong");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, 30));

        btnSlS.setBackground(new java.awt.Color(1, 198, 83));
        btnSlS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSlS.setForeground(new java.awt.Color(255, 255, 255));
        btnSlS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSlS.setText("số lượng sách");
        btnSlS.setToolTipText("số lượng sách được mượn trong ... ngày gầ nđây");
        btnSlS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSlS.setOpaque(true);
        btnSlS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSlSMouseClicked(evt);
            }
        });
        jPanel3.add(btnSlS, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 130, 30));

        btn_ms.setBackground(new java.awt.Color(1, 198, 83));
        btn_ms.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_ms.setForeground(new java.awt.Color(255, 255, 255));
        btn_ms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_ms.setText("mã sách");
        btn_ms.setToolTipText("số lượng sách được mượn theo mã sách");
        btn_ms.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ms.setOpaque(true);
        btn_ms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_msMouseClicked(evt);
            }
        });
        jPanel3.add(btn_ms, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 130, 30));

        btn_tc.setBackground(new java.awt.Color(1, 198, 83));
        btn_tc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_tc.setForeground(new java.awt.Color(255, 255, 255));
        btn_tc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_tc.setText("tiền cọc");
        btn_tc.setToolTipText("tổng tiền cọc trong ... ngày gần nhất");
        btn_tc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tc.setOpaque(true);
        btn_tc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tcMouseClicked(evt);
            }
        });
        jPanel3.add(btn_tc, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 130, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dmMouseClicked
        // TODO add your handling code here:
        
        try {
            // TODO add your handling code here:
            setLblColor(btn_dm);
            resetLblColor(btn_dg);
            resetLblColor(btn_nv);
            resetLblColor(btn_ms);
            resetLblColor(btnSlS);
            resetLblColor(btn_tc);
            
            short sn;
            
            String strSN = txtSN.getText().trim();
            
            if (strSN.equals("")){
                JOptionPane.showMessageDialog(null, "Số ngày không được để rỗng!");
                txtSN.requestFocus();
                return;
            }
            try {
                sn = Short.parseShort(strSN);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Số ngày '" + strSN + "' không hợp lệ!");
                txtSN.requestFocus();
                return;
            }
            
            ngay = sn;
            
            Date today = new Date(System.currentTimeMillis());
            
            MuonTraDAO.TK(tableTK, "SELECT NGAY_MUON AS [Ngày mượn], COUNT (MA_MUON_TRA) AS [Số lượng đơn được lập] "
                    + "FROM MUON_TRA "
                    + "WHERE DATEDIFF(DAY, NGAY_MUON, '" + today.toString() + "') BETWEEN 0 AND " + sn + " GROUP BY NGAY_MUON");
                    
                    //+ "WHERE NGAY_MUON BETWEEN '" + startingDay.toString() + "' AND '" + endDate.toString() + "' GROUP BY NGAY_MUON");

//                    + "WHERE NGAY_MUON >= '" + startingDay.toString() + "' "
//                            + "AND NGAY_MUON <= '" + endDate.toString()
//                    + "' GROUP BY NGAY_MUON");
            clickedButt = 3;
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(GUIThongKeNV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_dmMouseClicked

    private void btn_dgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dgMouseClicked
        try {
            // TODO add your handling code here:
            setLblColor(btn_dg);
            resetLblColor(btn_dm);
            resetLblColor(btn_nv);
            resetLblColor(btn_ms);
            resetLblColor(btnSlS);
            resetLblColor(btn_tc);
            
            MuonTraDAO.TK(tableTK, "SELECT MUON_TRA.MA_DOC_GIA AS [Mã độc giả], DOC_GIA.TEN_DOC_GIA AS [Tên độc giả], COUNT (MA_MUON_TRA) AS [Số lượng đơn đã mượn] FROM MUON_TRA, DOC_GIA WHERE DOC_GIA.MA_DOC_GIA = MUON_TRA.MA_DOC_GIA GROUP BY MUON_TRA.MA_DOC_GIA, DOC_GIA.TEN_DOC_GIA");
            clickedButt = 1;
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(GUIThongKeMT.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_dgMouseClicked

    private void btn_nvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nvMouseClicked
        // TODO add your handling code here:
        //        setLblColor(btn_ns);
        //        resetLblColor(btn_dt);
        //        resetLblColor(btn_gt);

        try {
            // TODO add your handling code here:
            setLblColor(btn_nv);
            resetLblColor(btn_dm);
            resetLblColor(btn_dg);
            resetLblColor(btn_ms);
            resetLblColor(btnSlS);
            resetLblColor(btn_tc);
            
            MuonTraDAO.TK(tableTK, "SELECT MUON_TRA.MA_NHAN_VIEN AS [Mã nhân viên], NHAN_VIEN.TEN_NHAN_VIEN AS [Tên nhân viên], COUNT (MA_MUON_TRA) AS [Số lượng đơn cho mượn] FROM MUON_TRA, NHAN_VIEN WHERE NHAN_VIEN.MA_NHAN_VIEN = MUON_TRA.MA_NHAN_VIEN GROUP BY MUON_TRA.MA_NHAN_VIEN, NHAN_VIEN.TEN_NHAN_VIEN");
            clickedButt = 2;
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(GUIThongKeNV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_nvMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:S
        if (clickedButt == 1)
            MuonTraDAO.InBieuMauThK(tableTK, "THỐNG KÊ SỐ LƯỢNG ĐƠN ĐÃ MƯỢN THEO ĐỘC GIẢ", "Mã độc giả","Tên độc giả", "Số đơn đã mượn");
        if (clickedButt == 2)
            MuonTraDAO.InBieuMauThK(tableTK, "THỐNG KÊ SỐ LƯỢNG ĐƠN ĐÃ CHO MƯỢN THEO NHÂN VIÊN", "Mã nhân viên","Tên nhân viên", "Số đơn đã cho mượn");
        if (clickedButt == 3)
            DocGiaDAO.TK_The_loai(tableTK, "Ngày", "THỐNG KÊ SỐ LƯỢNG ĐƠN ĐƯỢC LẬP TRONG " + ngay + " NGÀY GẦN NHẤT");
        if (clickedButt == 4)
            MuonTraDAO.InBieuMauThK(tableTK, "THỐNG KÊ SỐ LƯỢNG SÁCH ĐƯỢC MƯƠN THEO MÃ SÁCH", "Mã sách","Tên sách", "Tổng số sách được mượn");
        if (clickedButt == 5)
            DocGiaDAO.TK_The_loai(tableTK, "Ngày", "THỐNG KÊ SỐ LƯỢNG SÁCH ĐƯỢC MƯỢN TRONG " + ngay + " NGÀY GẦN NHẤT");
        if (clickedButt == 6)
            DocGiaDAO.TK_The_loai(tableTK, "Ngày", "THỐNG KÊ TỔNG TIỀN CỌC TRONG " + ngay + " NGÀY GẦN NHẤT");

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        setOpacity((float)0.8);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_jPanel3MouseReleased

    private void txtSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSNActionPerformed

    private void btnSlSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSlSMouseClicked
        // TODO add your handling code here:
       
        setLblColor(btnSlS);
        resetLblColor(btn_dm);
        resetLblColor(btn_dg);
        resetLblColor(btn_ms);
        resetLblColor(btn_nv);
        resetLblColor(btn_tc);
        
        try {
            
            short sn;

            String strSN = txtSN.getText().trim();

            if (strSN.equals("")) {
                JOptionPane.showMessageDialog(null, "Số ngày không được để rỗng!");
                txtSN.requestFocus();
                return;
            }
            try {
                sn = Short.parseShort(strSN);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Số ngày '" + strSN + "' không hợp lệ!");
                txtSN.requestFocus();
                return;
            }
            
            ngay = sn;

            Date today = new Date(System.currentTimeMillis());

            MuonTraDAO.TK(tableTK, "SELECT NGAY_MUON AS [Ngày mượn], SUM (SO_LUONG) AS [Số lượng sách cho mượn] "
                    + "FROM MUON_TRA, CHI_TIET_MUON "
                    + "WHERE CHI_TIET_MUON.MA_MUON_TRA = MUON_TRA.MA_MUON_TRA AND "
                    + "DATEDIFF(DAY, NGAY_MUON, '" + today.toString() + "') BETWEEN 0 AND " + sn 
                    + " GROUP BY NGAY_MUON");
            clickedButt = 5;
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIThongKeMT.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GUIThongKeMT.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSlSMouseClicked

    private void btn_msMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_msMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            setLblColor(btn_ms);
            resetLblColor(btn_dg);
            resetLblColor(btn_nv);
            resetLblColor(btn_dm);
            resetLblColor(btnSlS);
            resetLblColor(btn_tc);
            
            //"SELECT CHI_TIET_MUON.MA_SACH AS [Mã sách], SACH.TEN_SACH AS [Tên sách], SUM (CHI_TIET_MUON.SO_LUONG) AS [Số lượng được mượn] FROM CHI_TIET_MUON, SACH WHERE SACH.MA_SACH = CHI_TIET_MUON.MA_SACH GROUP BY CHI_TIET_MUON.MA_SACH, SACH.TEN_SACH"
            MuonTraDAO.TK(tableTK, "SELECT CHI_TIET_MUON.MA_SACH AS [Mã sách], SACH.TEN_SACH AS [Tên sách], SUM (CHI_TIET_MUON.SO_LUONG) AS [Số lượng được mượn] FROM CHI_TIET_MUON, SACH WHERE SACH.MA_SACH = CHI_TIET_MUON.MA_SACH GROUP BY CHI_TIET_MUON.MA_SACH, SACH.TEN_SACH");
            clickedButt = 4;
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(GUIThongKeNV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_msMouseClicked

    private void btn_tcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tcMouseClicked
        // TODO add your handling code here:
            
        setLblColor(btn_tc);
            resetLblColor(btn_dm);
            resetLblColor(btn_dg);
            resetLblColor(btn_nv);
            resetLblColor(btn_ms);
            resetLblColor(btnSlS);
            
            short sn;
            
            String strSN = txtSN.getText().trim();
            
            if (strSN.equals("")){
                JOptionPane.showMessageDialog(null, "Số ngày không được để rỗng!");
                txtSN.requestFocus();
                return;
            }
            try {
                sn = Short.parseShort(strSN);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Số ngày '" + strSN + "' không hợp lệ!");
                txtSN.requestFocus();
                return;
            }
            
            ngay = sn;
            
            Date today = new Date(System.currentTimeMillis());
            
            try {
            MuonTraDAO.TK(tableTK, "SELECT NGAY_MUON AS [Ngày mượn], SUM (TIEN_COC) AS [Tổng tiền cọc] "
                    + "FROM MUON_TRA "
                    + "WHERE DATEDIFF(DAY, NGAY_MUON, '" + today.toString() + "') BETWEEN 0 AND " + sn + " GROUP BY NGAY_MUON");
            clickedButt = 6;
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(GUIThongKeMT.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_tcMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIThongKeMT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIThongKeMT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIThongKeMT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIThongKeMT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIThongKeMT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSlS;
    private javax.swing.JLabel btn_dg;
    private javax.swing.JLabel btn_dm;
    private javax.swing.JLabel btn_ms;
    private javax.swing.JLabel btn_nv;
    private javax.swing.JLabel btn_tc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTK;
    private javax.swing.JTextField txtSN;
    // End of variables declaration//GEN-END:variables
}
