/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dal.SachDAO;
import dto.SachDTO;
import java.awt.event.ItemEvent;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author hiep.tt166077
 */
public class QuanLiSach extends javax.swing.JFrame {

    /**
     * Creates new form QuanLiSach
     */
    
    private String TieuChiTK = "ALL";
    String TenBaoCao = null;
    Boolean hienThiNhapTenBC = false;
    
    public QuanLiSach() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        txtMaS.requestFocus();
        txtMaS1.setEnabled(false);
        txtMaSDeXoa.setEnabled(false);
        SetModelToCombobox();
        Load_RefreshTable();
        TenBC.setVisible(false);
        buttXuatFile1.setVisible(false);
        //loadTable();
    }
    
    private void Load_RefreshTable(){
        try {
            SachDAO.LoadDuLieu(tableSach);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(QuanLiSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private Object[] loadColumnName(){
        return new Object[]{};
    }
    
    private Object[][] loadData(){
        return new Object[][]{};
    }
    
    private void loadTable(){
        TableModel dataModel = new DefaultTableModel(loadData(), loadColumnName());
        tableSach.setModel(dataModel);
    }
    
    private void SetModelToCombobox(){
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        ArrayList<String> list = new ArrayList<>();
        
        try {
            list = SachDAO.takeMaS();
            for(String i : list) model.addElement(i);
            jComboBoxMaS.setModel(model);
            jComboBoxMaS2.setModel(model);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLiSach.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLiSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private Boolean isNull(JTextField tf, String content, String tfName){
        
        if (content.equals("")){
            JOptionPane.showMessageDialog(null, tfName + " không được rỗng");
            tf.requestFocus();
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtMaS = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTenS = new javax.swing.JTextField();
        txtTenTG = new javax.swing.JTextField();
        txtTheLoai = new javax.swing.JTextField();
        txtNXB = new javax.swing.JTextField();
        txtNamXB = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtSL = new javax.swing.JTextField();
        buttThem = new javax.swing.JButton();
        buttReset = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txtMaS1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtTenS1 = new javax.swing.JTextField();
        txtTenTG1 = new javax.swing.JTextField();
        txtTheLoai1 = new javax.swing.JTextField();
        txtNXB1 = new javax.swing.JTextField();
        txtNamXB1 = new javax.swing.JTextField();
        txtDonGia1 = new javax.swing.JTextField();
        txtSL1 = new javax.swing.JTextField();
        buttThem1 = new javax.swing.JButton();
        buttReset1 = new javax.swing.JButton();
        jComboBoxMaS = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtMaSDeXoa = new javax.swing.JTextField();
        buttXoa = new javax.swing.JButton();
        jComboBoxMaS2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSach = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNoiDungTK = new javax.swing.JTextField();
        TieuChi = new javax.swing.JComboBox<>();
        buttTimKiem = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        TenBC = new javax.swing.JTextField();
        buttXuatFile1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1000, 600));

        jPanel1.setBackground(new java.awt.Color(240, 200, 190));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jLabel1.setText("Mã sách");

        jLabel2.setText("Tên sách");

        jLabel3.setText("Tên tác giả");

        jLabel4.setText("Thể loại");

        jLabel5.setText("Nhà xuất bản");

        jLabel6.setText("Năm xuất bản");

        jLabel7.setText("Đơn giá");

        jLabel8.setText("Số lượng");

        txtNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNXBActionPerformed(evt);
            }
        });

        txtSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLActionPerformed(evt);
            }
        });

        buttThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Plus_25px_1.png"))); // NOI18N
        buttThem.setText("Thêm");
        buttThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttThemActionPerformed(evt);
            }
        });

        buttReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/refresh.png"))); // NOI18N
        buttReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSL)
                                .addGap(10, 10, 10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDonGia)
                                .addGap(10, 10, 10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtNamXB))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenTG)
                                    .addComponent(txtTheLoai, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNXB)
                                    .addComponent(txtMaS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(txtTenS, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(10, 10, 10))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenTG))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTheLoai))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNXB))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamXB)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDonGia))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSL))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttReset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttThem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtMaS, txtTenS});

        jTabbedPane2.addTab("       Thêm     ", jPanel1);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jPanel4.setBackground(new java.awt.Color(240, 200, 190));

        txtMaS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaS1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Mã sách");

        jLabel10.setText("Tên sách");

        jLabel11.setText("Tên tác giả");

        jLabel12.setText("Thể loại");

        jLabel13.setText("Nhà xuất bản");

        jLabel14.setText("Năm xuất bản");

        jLabel15.setText("Đơn giá");

        jLabel16.setText("Số lượng");

        txtNXB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNXB1ActionPerformed(evt);
            }
        });

        txtSL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSL1ActionPerformed(evt);
            }
        });

        buttThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Edit_25px_1.png"))); // NOI18N
        buttThem1.setText("Sửa");
        buttThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttThem1ActionPerformed(evt);
            }
        });

        buttReset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/refresh.png"))); // NOI18N
        buttReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttReset1ActionPerformed(evt);
            }
        });

        jComboBoxMaS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxMaS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMaSItemStateChanged(evt);
            }
        });
        jComboBoxMaS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxMaSMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSL1)
                                    .addComponent(txtDonGia1))
                                .addContainerGap())
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(buttThem1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(buttReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtNamXB1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel9))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jComboBoxMaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMaS1))
                                    .addComponent(txtTheLoai1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenTG1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenS1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNXB1, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMaS1)
                    .addComponent(jComboBoxMaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTenS1))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTenTG1))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTheLoai1))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNXB1))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamXB1)
                    .addComponent(jLabel14))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtDonGia1))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtSL1))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTabbedPane2.addTab("        Sửa      ", jPanel2);

        jPanel3.setBackground(new java.awt.Color(240, 200, 190));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Nhập mã sách cần xóa hoặc chọn trên bảng");

        txtMaSDeXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSDeXoaActionPerformed(evt);
            }
        });

        buttXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Trash_Can_30px.png"))); // NOI18N
        buttXoa.setText("Xóa");
        buttXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttXoaActionPerformed(evt);
            }
        });

        jComboBoxMaS2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxMaS2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMaS2ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jComboBoxMaS2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtMaSDeXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(buttXoa)))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxMaS2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSDeXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(buttXoa)
                .addContainerGap())
        );

        jTabbedPane2.addTab("         Xóa         ", jPanel3);

        tableSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Tên tác giả", "Thể loại", "NXB", "Năm XB", "Đơn giá", "Số lượng"
            }
        ));
        tableSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSach);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_16px.png"))); // NOI18N
        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel18.setText("Tiêu chí");

        jLabel19.setText("Giá trị");

        TieuChi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả tiêu chí", "Mã sách", "Tên sách", "Tên tác giả", "Thể loại", "Nhà xuất bản", "Năm xuất bản", "Đơn giá", "Số lượng" }));
        TieuChi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TieuChiItemStateChanged(evt);
            }
        });

        buttTimKiem.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        buttTimKiem.setForeground(new java.awt.Color(204, 0, 204));
        buttTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Search.png"))); // NOI18N
        buttTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttTimKiemActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Sync_16px.png"))); // NOI18N
        jButton2.setText("Reset Bảng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Print_16px.png"))); // NOI18N
        jButton3.setText("Xuất ra file");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Add_File_16px.png"))); // NOI18N
        jButton4.setText("Thêm từ File");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Line_Chart_16px.png"))); // NOI18N
        jButton5.setText("Thống kê");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        TenBC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51)));
        TenBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenBCActionPerformed(evt);
            }
        });

        buttXuatFile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Enter_25px.png"))); // NOI18N
        buttXuatFile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttXuatFile1ActionPerformed(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Books/icons8_Book_45px_3.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Books/icons8_Book_45px_1.png"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Books/icons8_Book_Stack_45px.png"))); // NOI18N

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Books/icons8_Book_Stack_45px_1.png"))); // NOI18N

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Books/icons8_Book_45px_4.png"))); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Books/icons8_Book_45px.png"))); // NOI18N

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jMenu2.setText("Quản lí sách");

        jMenuItem3.setText("Hướng dẫn sử dụng");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(186, 186, 186)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel18)
                        .addGap(44, 44, 44)
                        .addComponent(TieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(TenBC, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel19)
                        .addGap(52, 52, 52)
                        .addComponent(txtNoiDungTK, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(buttTimKiem)
                        .addGap(236, 236, 236)
                        .addComponent(buttXuatFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel23)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel25)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel21)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel20)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel24)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel22)
                        .addGap(185, 185, 185)
                        .addComponent(jButton1))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(TieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TenBC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(txtNoiDungTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(buttXuatFile1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel24)
                    .addComponent(jLabel22)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNXBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNXBActionPerformed

    private void txtSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLActionPerformed

    private void buttResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttResetActionPerformed
        // TODO add your handling code here:
        txtMaS.setText("");
        txtTenS.setText("");
        txtTenTG.setText("");
        txtTheLoai.setText("");
        txtNXB.setText("");
        txtNamXB.setText("");
        txtDonGia.setText("");
        txtSL.setText("");
        //buttThem.setEnabled(false);
        
    }//GEN-LAST:event_buttResetActionPerformed

    private void buttThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttThemActionPerformed
        // TODO add your handling code here:
        String strMaS = txtMaS.getText();
        if (isNull(txtMaS, strMaS, "Mã sách")) return;
        if (SachDAO.isIDExistence(strMaS)){
            JOptionPane.showMessageDialog(null, "Mã sách " + strMaS + " đã có trong hệ thống");
            txtMaS.requestFocus();
            return;
        }
        
        String strTenS = txtTenS.getText();
        if (isNull(txtTenS, strTenS, "Tên sách")) return;
        
        String strTenTG = txtTenTG.getText();
        if (isNull(txtTenTG, strTenTG, "Tên tác giả")) return;
        
        String strTheLoai = txtTheLoai.getText();
        if (isNull(txtTheLoai, strTheLoai, "Thê loại")) return;
        
        String strNXB = txtNXB.getText();
        if (isNull(txtNXB, strNXB, "NXB")) return;
        
        String strNamXB = txtNamXB.getText();
        if (isNull(txtNamXB, strNamXB, "Năm xuất bản")) return;
        try{
            Short.parseShort(strNamXB);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Giá trị '" + strNamXB + "' không hợp lệ!");
            txtNamXB.requestFocus();
            return;
        }
        
        String strDonGia = txtDonGia.getText();
        if (isNull(txtDonGia, strDonGia, "Đơn giá")) return;
        try{
            Integer.parseInt(strDonGia);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Giá trị '" + strDonGia + "' không hợp lệ!");
            txtDonGia.requestFocus();
            return;
        }
        
        String strSL = txtSL.getText();
        if (isNull(txtSL, strSL, "Số lượng")) return;
        try{
            Short.parseShort(strSL);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Giá trị '" + strSL + "' không hợp lệ!");
            txtSL.requestFocus();
            return;
        }
        
        SachDTO newBook = new SachDTO(strMaS, strTenS, strTenTG, strTheLoai, strNXB, Short.parseShort(strNamXB), Integer.parseInt(strDonGia), Short.parseShort(strSL));
        
        try {
            SachDAO.Them(newBook);
            JOptionPane.showMessageDialog(null, "Thêm thành công!");
            SetModelToCombobox();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLiSach.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Thêm thất bại!");
        } catch (SQLException ex) {
            Logger.getLogger(QuanLiSach.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Thêm thất bại!");
        }
        
        Load_RefreshTable();
    }//GEN-LAST:event_buttThemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //gui.DangNhap.main(null);
        Menu CNFrame = new Menu();
        CNFrame.setLocationRelativeTo(null);
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNXB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNXB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNXB1ActionPerformed

    private void txtSL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSL1ActionPerformed

    private void buttThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttThem1ActionPerformed
        // TODO add your handling code here:
//        String strMaS = txtMaS1.getText();
//        String strTenS = txtTenS1.getText();
//        String strTenTG = txtTenTG1.getText();
//        String strTheLoai = txtTheLoai1.getText();
//        String strNXB = txtNXB1.getText();
//        String strNamXB = txtNamXB1.getText();
//        String strSL = txtSL1.getText();
//        String strDonGia = txtDonGia1.getText();

        String strMaS = txtMaS1.getText();
        if (isNull(txtMaS1, strMaS, "Mã sách")) return;
        if (!SachDAO.isIDExistence(strMaS.trim())){
            JOptionPane.showMessageDialog(null, "Mã sách " + strMaS.trim() + " chưa có trong hệ thống");
            txtMaS.requestFocus();
            return;
        }
        
        String strTenS = txtTenS1.getText();
        if (isNull(txtTenS1, strTenS, "Tên sách")) return;
        
        String strTenTG = txtTenTG1.getText();
        if (isNull(txtTenTG1, strTenTG, "Tên tác giả")) return;
        
        String strTheLoai = txtTheLoai1.getText();
        if (isNull(txtTheLoai1, strTheLoai, "Thê loại")) return;
        
        String strNXB = txtNXB1.getText();
        if (isNull(txtNXB1, strNXB, "NXB")) return;
        
        String strNamXB = txtNamXB1.getText();
        if (isNull(txtNamXB1, strNamXB, "Năm xuất bản")) return;
        try{
            Short.parseShort(strNamXB);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Giá trị '" + strNamXB + "' không hợp lệ!");
            txtNamXB1.requestFocus();
            return;
        }
        
        String strDonGia = txtDonGia1.getText();
        if (isNull(txtDonGia1, strDonGia, "Đơn giá")) return;
        try{
            Integer.parseInt(strDonGia);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Giá trị '" + strDonGia + "' không hợp lệ!");
            txtDonGia1.requestFocus();
            return;
        }
        
        String strSL = txtSL1.getText();
        if (isNull(txtSL1, strSL, "Số lượng")) return;
        try{
            Short.parseShort(strSL);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Giá trị '" + strSL + "' không hợp lệ!");
            txtSL1.requestFocus();
            return;
        }
        
        SachDTO newBook = new SachDTO(strMaS, strTenS, strTenTG, strTheLoai, strNXB, Short.parseShort(strNamXB), Integer.parseInt(strDonGia), Short.parseShort(strSL));
        
        try {
            SachDAO.ModifyRecord(newBook);
            JOptionPane.showMessageDialog(null, "Sửa thành công!");
            Load_RefreshTable();
        } catch (SQLException ex) {
            Logger.getLogger(QuanLiSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttThem1ActionPerformed

    private void buttReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttReset1ActionPerformed
        // TODO add your handling code here:
        txtMaS1.setText("");
        txtTenS1.setText("");
        txtTenTG1.setText("");
        txtTheLoai1.setText("");
        txtNXB1.setText("");
        txtNamXB1.setText("");
        txtDonGia1.setText("");
        txtSL1.setText("");
    }//GEN-LAST:event_buttReset1ActionPerformed

    private void tableSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSachMouseClicked
        // TODO add your handling code here:
        int row = tableSach.getSelectedRow();
        String MaS = (tableSach.getModel().getValueAt(row, 0)).toString();
        SachDTO newDTO = null;
        try {
            newDTO = SachDAO.LoadRowContent(MaS);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLiSach.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLiSach.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (newDTO == null){
        }
        else{
            txtMaS1.setText(newDTO.getMaSach());
            txtMaSDeXoa.setText(newDTO.getMaSach());
            txtTenS1.setText(newDTO.getTenSach());
            txtTenTG1.setText(newDTO.getTenTacGia());
            txtTheLoai1.setText(newDTO.getTheLoai());
            txtNXB1.setText(newDTO.getNXB());
            txtNamXB1.setText(Short.toString(newDTO.getNamXuatBan()));
            txtDonGia1.setText(Integer.toString(newDTO.getDonGia()));
            txtSL1.setText(Short.toString(newDTO.getSoLuong()));
        }
    }//GEN-LAST:event_tableSachMouseClicked

    private void buttXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttXoaActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa sách có mã " + txtMaSDeXoa.getText() + "?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION){
            SachDAO.DeleteReCord(txtMaSDeXoa.getText());
            SetModelToCombobox();
            JOptionPane.showMessageDialog(null, "Xoá thành công!");
            Load_RefreshTable();
        }
    }//GEN-LAST:event_buttXoaActionPerformed

    private void txtMaSDeXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSDeXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSDeXoaActionPerformed

    private void txtMaS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaS1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaS1ActionPerformed

    private void buttTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttTimKiemActionPerformed
        try {
            // TODO add your handling code here:
            if (!TieuChiTK.equals("ALL"))
                SachDAO.Search_Load_Table(TieuChiTK, txtNoiDungTK.getText(), tableSach);
            else SachDAO.Search_Load_Table(txtNoiDungTK.getText(), tableSach);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QuanLiSach.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(QuanLiSach.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buttTimKiemActionPerformed

    private void TieuChiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TieuChiItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED){
            
            if (TieuChi.getSelectedItem().equals("Mã sách")){
                TieuChiTK = "MA_SACH";
            }
            else if(TieuChi.getSelectedItem().equals("Tên sách")){
                TieuChiTK = "TEN_SACH";
            }
            else if(TieuChi.getSelectedItem().equals("Tên tác giả")){
                TieuChiTK = "TEN_TAC_GIA";
            }
            else if(TieuChi.getSelectedItem().equals("Thể loại")){
                TieuChiTK = "THE_LOAI";
            }
            else if(TieuChi.getSelectedItem().equals("Nhà xuất bản")){
                TieuChiTK = "NXB";
            }
            else if(TieuChi.getSelectedItem().equals("Năm xuất bản")){
                TieuChiTK = "NAM_XUAT_BAN";
            }
            else if(TieuChi.getSelectedItem().equals("Đơn giá")){
                TieuChiTK = "DON_GIA";
            }
            else if(TieuChi.getSelectedItem().equals("Số lượng")){
                TieuChiTK = "SO_LUONG";
            }
            else{
                TieuChiTK = "ALL";
            }
        }
    }//GEN-LAST:event_TieuChiItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Load_RefreshTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        HDSach HD = new HDSach();
        HD.setVisible(true);
        HD.setLocationRelativeTo(null);
        HD.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
//        JFileChooser output  = new JFileChooser();
//        output.setDialogTitle("Tìm địa điểm lưu file và tên file");
//        if (output.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
//            
//            File file = output.getSelectedFile();
//            try {
//                SachDAO.XuatRaFile(file, tableSach.getModel());
//                JOptionPane.showMessageDialog(null, "Xuất thành công " + file.getAbsolutePath());
//            } catch (ClassNotFoundException ex) {
//                Logger.getLogger(QuanLiSach.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (SQLException ex) {
//                Logger.getLogger(QuanLiSach.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (IOException ex) {
//                Logger.getLogger(QuanLiSach.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }

        if (hienThiNhapTenBC) {
            TenBC.setVisible(false);
            buttXuatFile1.setVisible(false);
            hienThiNhapTenBC = false;
        } else {
            TenBC.setVisible(true);
            buttXuatFile1.setVisible(true);
            hienThiNhapTenBC = true;
            TenBC.requestFocus();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFileChooser input  = new JFileChooser();
        input.setDialogTitle("Tìm file nguồn");
        if (input.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            
            File file = input.getSelectedFile();
            try {
                SachDAO.ThemTuFile(file);
                Load_RefreshTable();
                SetModelToCombobox();
                JOptionPane.showMessageDialog(null, "Thêm thành công!");
            } catch (ClassNotFoundException | SQLException | IOException ex) {
                JOptionPane.showMessageDialog(null, "Thêm thất bại!");
                Logger.getLogger(QuanLiSach.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBoxMaSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxMaSMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMaSMouseClicked

    private void jComboBoxMaSItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMaSItemStateChanged
        // TODO add your handling code here:
        txtMaS1.setText(jComboBoxMaS.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxMaSItemStateChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //ThongKeSach.main(null);
        new ThongKeSach().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBoxMaS2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMaS2ItemStateChanged
        // TODO add your handling code here:
        txtMaSDeXoa.setText(jComboBoxMaS2.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBoxMaS2ItemStateChanged

    private void TenBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenBCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenBCActionPerformed

    private void buttXuatFile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttXuatFile1ActionPerformed
        // TODO add your handling code here:
        
        TenBaoCao = TenBC.getText();
        TenBC.setVisible(false);
        buttXuatFile1.setVisible(false);
        hienThiNhapTenBC = false;
        SachDAO.XuatBieuMauTimKiem(tableSach, TenBaoCao);
    }//GEN-LAST:event_buttXuatFile1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_QuanLiSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_QuanLiSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_QuanLiSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_QuanLiSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiSach().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TenBC;
    private javax.swing.JComboBox<String> TieuChi;
    private javax.swing.JButton buttReset;
    private javax.swing.JButton buttReset1;
    private javax.swing.JButton buttThem;
    private javax.swing.JButton buttThem1;
    private javax.swing.JButton buttTimKiem;
    private javax.swing.JButton buttXoa;
    private javax.swing.JButton buttXuatFile1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBoxMaS;
    private javax.swing.JComboBox<String> jComboBoxMaS2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tableSach;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtDonGia1;
    private javax.swing.JTextField txtMaS;
    private javax.swing.JTextField txtMaS1;
    private javax.swing.JTextField txtMaSDeXoa;
    private javax.swing.JTextField txtNXB;
    private javax.swing.JTextField txtNXB1;
    private javax.swing.JTextField txtNamXB;
    private javax.swing.JTextField txtNamXB1;
    private javax.swing.JTextField txtNoiDungTK;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtSL1;
    private javax.swing.JTextField txtTenS;
    private javax.swing.JTextField txtTenS1;
    private javax.swing.JTextField txtTenTG;
    private javax.swing.JTextField txtTenTG1;
    private javax.swing.JTextField txtTheLoai;
    private javax.swing.JTextField txtTheLoai1;
    // End of variables declaration//GEN-END:variables
}
