/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dal.DocGiaDAO;
import dal.NhanVienDAO;
import dal.TaiKhoanDAO;
import dto.NhanVienDTO;
import dto.TaiKhoanDTO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hiep.tt166077
 */
public class ThongTinNV extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinNV
     */
    String staffID = null;
    boolean isDMKvisible = false;

    public ThongTinNV(String staffID) {
        
        this.staffID = staffID;
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        loadTT();
    }
    
    private void loadTT(){
        
        panDMK.setVisible(false);
        
        NhanVienDTO newDTO = null;
        try {
            newDTO = NhanVienDAO.LoadRowContent(this.staffID);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ThongTinNV.class.getName()).log(Level.SEVERE, null, ex);
        }

        txtTenDG.setText(newDTO.getTenNV());
        txtmadg.setText(newDTO.getMaNV().trim());
        txtgt.setText(newDTO.getGioiTinh());
        txtcmnd.setText(Long.toString(newDTO.getCMND()));
        txtngays.setText(newDTO.getNgaySinh().toString());
        txtdiachi.setText(newDTO.getDiaChi());
        txtsdt.setText(Long.toString(newDTO.getSDT()));
        txtemail.setText(newDTO.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panTT = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtmadg = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtgt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtcmnd = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtngays = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtTenDG = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        panDMK = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtHT = new javax.swing.JPasswordField();
        txtNew = new javax.swing.JPasswordField();
        txtReNew = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panTT.setBackground(new java.awt.Color(255, 255, 255));
        panTT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("Mã nhân viên");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 29, -1, -1));

        txtmadg.setEditable(false);
        txtmadg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtmadg.setForeground(new java.awt.Color(51, 51, 51));
        txtmadg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmadg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmadgActionPerformed(evt);
            }
        });
        jPanel4.add(txtmadg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 26, 198, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("Giới tính");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 81, 58, -1));

        txtgt.setEditable(false);
        txtgt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtgt.setForeground(new java.awt.Color(51, 51, 51));
        txtgt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtgt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgtActionPerformed(evt);
            }
        });
        jPanel4.add(txtgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 78, 198, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("CMND");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 138, -1, -1));

        txtcmnd.setEditable(false);
        txtcmnd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtcmnd.setForeground(new java.awt.Color(51, 51, 51));
        txtcmnd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcmnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcmndActionPerformed(evt);
            }
        });
        jPanel4.add(txtcmnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 135, 198, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Ngày sinh");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 198, -1, -1));

        txtngays.setEditable(false);
        txtngays.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtngays.setForeground(new java.awt.Color(51, 51, 51));
        txtngays.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtngays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngaysActionPerformed(evt);
            }
        });
        jPanel4.add(txtngays, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 195, 198, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Địa chỉ");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 29, -1, -1));

        txtdiachi.setEditable(false);
        txtdiachi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtdiachi.setForeground(new java.awt.Color(51, 51, 51));
        txtdiachi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdiachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiachiActionPerformed(evt);
            }
        });
        jPanel4.add(txtdiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 26, 198, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Số diện thoại");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 81, -1, -1));

        txtsdt.setEditable(false);
        txtsdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsdt.setForeground(new java.awt.Color(51, 51, 51));
        txtsdt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsdtActionPerformed(evt);
            }
        });
        jPanel4.add(txtsdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 78, 198, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Email");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 138, -1, -1));

        txtemail.setEditable(false);
        txtemail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtemail.setForeground(new java.awt.Color(51, 51, 51));
        txtemail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel4.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 135, 198, -1));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 58, 182, -1));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 179, -1));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 175, 176, -1));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 227, 175, 10));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 58, 176, -1));
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 177, -1));
        jPanel4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 167, 175, -1));

        panTT.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 242, 710, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Account_100px.png"))); // NOI18N
        panTT.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 62, -1, -1));

        txtTenDG.setEditable(false);
        txtTenDG.setBackground(new java.awt.Color(255, 255, 255));
        txtTenDG.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTenDG.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTenDG.setBorder(null);
        txtTenDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDGActionPerformed(evt);
            }
        });
        panTT.add(txtTenDG, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 173, 230, -1));

        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Password_25px.png"))); // NOI18N
        jLabel7.setText("đổi mật khẩu");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        panTT.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jLabel9.setText("Mật khẩu hiện tại");

        jLabel10.setText("Mật khẩu mới");

        jLabel12.setText("Nhập lại mật khẩu mới");

        txtHT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHTActionPerformed(evt);
            }
        });

        txtNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Ok_48px.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panDMKLayout = new javax.swing.GroupLayout(panDMK);
        panDMK.setLayout(panDMKLayout);
        panDMKLayout.setHorizontalGroup(
            panDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDMKLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addGap(22, 22, 22)
                .addGroup(panDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtReNew, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(txtNew)
                    .addComponent(txtHT))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDMKLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(49, 49, 49))
        );
        panDMKLayout.setVerticalGroup(
            panDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDMKLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panDMKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtReNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panTT.add(panDMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Reply_Arrow_30px.png"))); // NOI18N
        jLabel2.setToolTipText("Quay lại menu");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        panTT.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ahihi.jpg"))); // NOI18N
        panTT.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 1040, 1040));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panTT, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panTT, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmadgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmadgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmadgActionPerformed

    private void txtgtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgtActionPerformed

    private void txtcmndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcmndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcmndActionPerformed

    private void txtngaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtngaysActionPerformed

    private void txtdiachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiachiActionPerformed

    private void txtsdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsdtActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtTenDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDGActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        if (!isDMKvisible){
            panDMK.setVisible(true);
            txtHT.requestFocus();
            isDMKvisible = true;
        } else {
            panDMK.setVisible(false);
            isDMKvisible = false;
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void txtHTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHTActionPerformed

    private void txtNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        try {
            // TODO add your handling code here:
            TaiKhoanDTO newDTO = TaiKhoanDAO.XacThuc(this.staffID, txtHT.getText());
            if (newDTO == null){
                JOptionPane.showMessageDialog(null, "Mật khẩu không đúng, vui lòng nhập lại!");
                txtHT.setText("");
                txtHT.requestFocus();
                return;
            }

            if (!txtReNew.getText().equals(txtNew.getText())){
                JOptionPane.showMessageDialog(null, "Mật khẩu nhập lại không đúng, vui lòng nhập lại!");
                txtNew.setText(""); txtReNew.setText("");
                txtNew.requestFocus();
                return;
            }

            TaiKhoanDAO.CapNhat(this.staffID, txtNew.getText());
            JOptionPane.showMessageDialog(null, "Cập nhật mật khẩu thành công!");

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(GUITimKiemSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        Menu2 CNFrame = new Menu2(this.staffID);
        CNFrame.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ThongTinNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ThongTinNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ThongTinNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ThongTinNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ThongTinNV().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPanel panDMK;
    private javax.swing.JPanel panTT;
    private javax.swing.JPasswordField txtHT;
    private javax.swing.JPasswordField txtNew;
    private javax.swing.JPasswordField txtReNew;
    private javax.swing.JTextField txtTenDG;
    private javax.swing.JTextField txtcmnd;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtgt;
    private javax.swing.JTextField txtmadg;
    private javax.swing.JTextField txtngays;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables
}
