/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bll;

import gui.*;
import dal.DocGiaDAO;
import dto.DocGiaDTO;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author hiep.tt166077
 */
public class testQuanLiDocGia extends javax.swing.JFrame {

    /**
     * Creates new form GUIQuanLiDocGia
     */
    byte CN = 0;
    String TieuChiTK = "ALL";

    public testQuanLiDocGia() {
        initComponents();
        setLocationRelativeTo(null);
        Load_RefreshTable();
        SetModelToCombobox();
        disableTextboxes();
        setAllUnFocus();
    }

    private void Load_RefreshTable() {

        try {
            DocGiaDAO.LoadDuLieu(tableDG);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(testQuanLiDocGia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(testQuanLiDocGia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void disableTextboxes() {

        txtmadg.setEnabled(false);
        txttendg.setEnabled(false);
        txtgt.setEnabled(false);
        txtcmnd.setEnabled(false);
        txtngays.setEnabled(false);
        txtdiachi.setEnabled(false);
        txtsdt.setEnabled(false);
        txtemail.setEnabled(false);
        txttaikhoan.setEnabled(false);
        txttienphat.setEnabled(false);
        buttPanexecute.setEnabled(false);
        jComboBox2.setEnabled(false);
        jComboBox3.setEnabled(false);

    }

    private void setAllUnFocus() {
        focusThem.setBackground(new Color(240, 240, 240));
        focusThemFile.setBackground(new Color(240, 240, 240));
        focusSua.setBackground(new Color(240, 240, 240));
        focusXoa.setBackground(new Color(240, 240, 240));
        focusTK.setBackground(new Color(240, 240, 240));
    }

    private void unFocus(JPanel[] list) {
        for (byte i = 0; i < list.length; i++) {
            list[i].setOpaque(false);
        }
        for (byte i = 0; i < list.length; i++) {
            list[i].setBackground(new Color(240, 240, 240));
        }
    }

    private void SetModelToCombobox() {

        DefaultComboBoxModel model = new DefaultComboBoxModel();
        ArrayList<String> list = new ArrayList<>();

        try {
            list = DocGiaDAO.takeMaDG();
            for (String i : list) {
                model.addElement(i);
            }
            jComboBox2.setModel(model);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(testQuanLiDocGia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(testQuanLiDocGia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private Boolean isNull(JTextField tf, String content, String tfName) {

        if (content.equals("")) {
            JOptionPane.showMessageDialog(null, tfName + " không được rỗng");
            tf.requestFocus();
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDG = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        buttPanSua = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        focusSua = new javax.swing.JPanel();
        buttPanThem = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        focusThem = new javax.swing.JPanel();
        buttPanXoa = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        focusXoa = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtmadg = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtgt = new javax.swing.JTextField();
        txtcmnd = new javax.swing.JTextField();
        txttendg = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtngays = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttaikhoan = new javax.swing.JTextField();
        txttienphat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        buttPanThemFile = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        focusThemFile = new javax.swing.JPanel();
        buttPanTK = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        focusTK = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        SearchingContent = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        buttXuatFile = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        TieuChi = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        buttPanexecute = new javax.swing.JLabel();
        ExecuteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(228, 228, 228));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1086, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 27, -1, -1));

        jPanel3.setBackground(new java.awt.Color(35, 111, 22));
        jPanel3.setPreferredSize(new java.awt.Dimension(5, 600));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, 300, 10));

        tableDG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableDG.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDG.setGridColor(new java.awt.Color(255, 255, 255));
        tableDG.setRowHeight(20);
        tableDG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDGMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDG);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 550, 250));

        jPanel6.setBackground(new java.awt.Color(228, 228, 228));
        jPanel6.setPreferredSize(new java.awt.Dimension(5, 600));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 600));

        jPanel7.setBackground(new java.awt.Color(12, 120, 241));
        jPanel7.setMaximumSize(new java.awt.Dimension(3, 600));
        jPanel7.setPreferredSize(new java.awt.Dimension(3, 600));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 500, 10));

        jPanel8.setBackground(new java.awt.Color(252, 72, 68));
        jPanel8.setPreferredSize(new java.awt.Dimension(5, 600));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 460, 160, 10));

        buttPanSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttPanSuaMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Edit_30px.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sửa");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        focusSua.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout focusSuaLayout = new javax.swing.GroupLayout(focusSua);
        focusSua.setLayout(focusSuaLayout);
        focusSuaLayout.setHorizontalGroup(
            focusSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        focusSuaLayout.setVerticalGroup(
            focusSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout buttPanSuaLayout = new javax.swing.GroupLayout(buttPanSua);
        buttPanSua.setLayout(buttPanSuaLayout);
        buttPanSuaLayout.setHorizontalGroup(
            buttPanSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttPanSuaLayout.createSequentialGroup()
                .addComponent(focusSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(buttPanSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttPanSuaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(buttPanSuaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        buttPanSuaLayout.setVerticalGroup(
            buttPanSuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttPanSuaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(buttPanSuaLayout.createSequentialGroup()
                .addComponent(focusSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(buttPanSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 60, 60));

        buttPanThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttPanThemMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Plus_Math_30px.png"))); // NOI18N

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thêm");
        jLabel4.setFocusable(false);
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        focusThem.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout focusThemLayout = new javax.swing.GroupLayout(focusThem);
        focusThem.setLayout(focusThemLayout);
        focusThemLayout.setHorizontalGroup(
            focusThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        focusThemLayout.setVerticalGroup(
            focusThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout buttPanThemLayout = new javax.swing.GroupLayout(buttPanThem);
        buttPanThem.setLayout(buttPanThemLayout);
        buttPanThemLayout.setHorizontalGroup(
            buttPanThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttPanThemLayout.createSequentialGroup()
                .addComponent(focusThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(buttPanThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttPanThemLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addGroup(buttPanThemLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        buttPanThemLayout.setVerticalGroup(
            buttPanThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttPanThemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(buttPanThemLayout.createSequentialGroup()
                .addComponent(focusThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(buttPanThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 60, 60));

        buttPanXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttPanXoaMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Trash_Can_30px.png"))); // NOI18N

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Xóa");

        focusXoa.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout focusXoaLayout = new javax.swing.GroupLayout(focusXoa);
        focusXoa.setLayout(focusXoaLayout);
        focusXoaLayout.setHorizontalGroup(
            focusXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        focusXoaLayout.setVerticalGroup(
            focusXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout buttPanXoaLayout = new javax.swing.GroupLayout(buttPanXoa);
        buttPanXoa.setLayout(buttPanXoaLayout);
        buttPanXoaLayout.setHorizontalGroup(
            buttPanXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttPanXoaLayout.createSequentialGroup()
                .addComponent(focusXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(buttPanXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        buttPanXoaLayout.setVerticalGroup(
            buttPanXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttPanXoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(buttPanXoaLayout.createSequentialGroup()
                .addComponent(focusXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(buttPanXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_30px.png"))); // NOI18N
        jLabel7.setToolTipText("Quay lại Menu");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));

        jPanel16.setBackground(new java.awt.Color(131, 84, 135));
        jPanel16.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Mã độc giả");
        jPanel16.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtmadg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtmadg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmadgActionPerformed(evt);
            }
        });
        jPanel16.add(txtmadg, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 67, 90, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Tên độc giả");
        jPanel16.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 110, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Giới tính");
        jPanel16.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 58, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("CMND");
        jPanel16.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txtgt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtgt.setText("Nam");
        txtgt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgtActionPerformed(evt);
            }
        });
        jPanel16.add(txtgt, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 147, 90, -1));

        txtcmnd.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtcmnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcmndActionPerformed(evt);
            }
        });
        jPanel16.add(txtcmnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 187, 191, -1));

        txttendg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txttendg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttendgActionPerformed(evt);
            }
        });
        jPanel16.add(txttendg, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 107, 191, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Địa chỉ");
        jPanel16.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Email");
        jPanel16.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Số diện thoại");
        jPanel16.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tài khoản");
        jPanel16.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setText("Tiền phạt");
        jPanel16.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 699, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Ngày sinh");
        jPanel16.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        txtngays.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtngays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtngaysActionPerformed(evt);
            }
        });
        jPanel16.add(txtngays, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 227, 191, -1));

        txtdiachi.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtdiachi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiachiActionPerformed(evt);
            }
        });
        jPanel16.add(txtdiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 267, 191, -1));

        txtsdt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtsdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsdtActionPerformed(evt);
            }
        });
        jPanel16.add(txtsdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 307, 191, -1));

        txtemail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel16.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 347, 191, -1));

        txttaikhoan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txttaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttaikhoanActionPerformed(evt);
            }
        });
        jPanel16.add(txttaikhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 387, 191, -1));

        txttienphat.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txttienphat.setText("0");
        txttienphat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttienphatActionPerformed(evt);
            }
        });
        jPanel16.add(txttienphat, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 427, 191, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tiền phạt");
        jPanel16.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jPanel16.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 100, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        jPanel16.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 100, -1));

        jPanel1.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 320, 480));

        jPanel14.setBackground(new java.awt.Color(218, 36, 107));
        jPanel14.setPreferredSize(new java.awt.Dimension(5, 600));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 250, 10));

        jPanel15.setBackground(new java.awt.Color(35, 111, 22));
        jPanel15.setPreferredSize(new java.awt.Dimension(5, 600));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 300, 10));

        buttPanThemFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttPanThemFileMouseClicked(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Add_File_30px.png"))); // NOI18N

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Từ File");
        jLabel13.setFocusable(false);
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        focusThemFile.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout focusThemFileLayout = new javax.swing.GroupLayout(focusThemFile);
        focusThemFile.setLayout(focusThemFileLayout);
        focusThemFileLayout.setHorizontalGroup(
            focusThemFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        focusThemFileLayout.setVerticalGroup(
            focusThemFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout buttPanThemFileLayout = new javax.swing.GroupLayout(buttPanThemFile);
        buttPanThemFile.setLayout(buttPanThemFileLayout);
        buttPanThemFileLayout.setHorizontalGroup(
            buttPanThemFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttPanThemFileLayout.createSequentialGroup()
                .addComponent(focusThemFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(buttPanThemFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttPanThemFileLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addContainerGap())
                    .addGroup(buttPanThemFileLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        buttPanThemFileLayout.setVerticalGroup(
            buttPanThemFileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttPanThemFileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(buttPanThemFileLayout.createSequentialGroup()
                .addComponent(focusThemFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(buttPanThemFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, 60));

        buttPanTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttPanTKMouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Line_Chart_30px.png"))); // NOI18N

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Th. Kê");

        focusTK.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout focusTKLayout = new javax.swing.GroupLayout(focusTK);
        focusTK.setLayout(focusTKLayout);
        focusTKLayout.setHorizontalGroup(
            focusTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        focusTKLayout.setVerticalGroup(
            focusTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout buttPanTKLayout = new javax.swing.GroupLayout(buttPanTK);
        buttPanTK.setLayout(buttPanTKLayout);
        buttPanTKLayout.setHorizontalGroup(
            buttPanTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttPanTKLayout.createSequentialGroup()
                .addComponent(focusTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(buttPanTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        buttPanTKLayout.setVerticalGroup(
            buttPanTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttPanTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(buttPanTKLayout.createSequentialGroup()
                .addComponent(focusTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(buttPanTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, 60));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 200, -1));

        SearchingContent.setBackground(new java.awt.Color(247, 247, 247));
        SearchingContent.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        SearchingContent.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SearchingContent.setBorder(null);
        jPanel1.add(SearchingContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 200, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Search_Property_73px.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        buttXuatFile.setBackground(new java.awt.Color(247, 247, 247));
        buttXuatFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Save_30px_1.png"))); // NOI18N
        buttXuatFile.setToolTipText("Xuất biểu mẫu");
        buttXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttXuatFileActionPerformed(evt);
            }
        });
        jPanel1.add(buttXuatFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 40, -1));

        jButton2.setBackground(new java.awt.Color(247, 247, 247));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Go_30px.png"))); // NOI18N
        jButton2.setToolTipText("Tìm kiếm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 40, -1));

        jButton3.setBackground(new java.awt.Color(247, 247, 247));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Refresh_30px.png"))); // NOI18N
        jButton3.setToolTipText("Reset bảng");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 40, -1));

        TieuChi.setBackground(new java.awt.Color(232, 232, 232));
        TieuChi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả tiêu chí", "Mã độc giả", "Tên độc giả", "Giới tính", "CMND", "Ngày sinh", "Địa chỉ", "Số điện thoại", "Email", "Tài khoản", "Tiền phạt" }));
        TieuChi.setToolTipText("Tiêu chí tìm kiếm");
        TieuChi.setBorder(null);
        TieuChi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TieuChiItemStateChanged(evt);
            }
        });
        jPanel1.add(TieuChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, 140, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Close_Window_20px_1.png"))); // NOI18N
        jLabel17.setToolTipText("Đóng chương trình");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 20, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText(">>>QUẢN LÍ ĐỘC GIẢ<<<");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 320, 30));

        buttPanexecute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Play_50px.png"))); // NOI18N
        buttPanexecute.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttPanexecuteMouseClicked(evt);
            }
        });
        jPanel1.add(buttPanexecute, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, -1, -1));

        ExecuteLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.add(ExecuteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmadgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmadgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmadgActionPerformed

    private void txtgtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgtActionPerformed

    private void txtcmndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcmndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcmndActionPerformed

    private void txttendgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttendgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttendgActionPerformed

    private void txtngaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtngaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtngaysActionPerformed

    private void txtdiachiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiachiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiachiActionPerformed

    private void txtsdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsdtActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txttaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttaikhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttaikhoanActionPerformed

    private void txttienphatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttienphatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttienphatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            DocGiaDAO.Search_Load_Table(TieuChiTK, SearchingContent.getText(), tableDG);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(testQuanLiDocGia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Load_RefreshTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableDGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDGMouseClicked
        // TODO add your handling code here:
        int row = tableDG.getSelectedRow();
        String MaDG = (tableDG.getModel().getValueAt(row, 0)).toString();
        DocGiaDTO newDTO = null;
        try {
            newDTO = DocGiaDAO.LoadRowContent(MaDG);
        } catch (SQLException ex) {
            Logger.getLogger(testQuanLiDocGia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(testQuanLiDocGia.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (newDTO == null) {
        } else {
            txtmadg.setText(newDTO.getMaDG());
            txttendg.setText(newDTO.getTenDG());
            txtgt.setText(newDTO.getGioiTinh());
            txtcmnd.setText(Long.toString(newDTO.getCMND()));
            txtngays.setText(newDTO.getNgaySinh().toString());
            txtdiachi.setText(newDTO.getDiaChi());
            txtsdt.setText(Long.toString(newDTO.getSDT()));
            txtemail.setText(newDTO.getEmail());
            txttaikhoan.setText(Long.toString(newDTO.getTaiKhoan()));
            txttienphat.setText(Long.toString(newDTO.getTienPhat()));
        }
    }//GEN-LAST:event_tableDGMouseClicked

    private void buttPanThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttPanThemMouseClicked
        // TODO add your handling code here:

        focusThem.setOpaque(true);
        focusThem.setBackground(Color.red);
        unFocus(new JPanel[]{focusThemFile, focusSua, focusXoa, focusTK});
        CN = 1;
        ExecuteLabel.setText("Thêm");

        txtmadg.setEnabled(true);
        txttendg.setEnabled(true);
        txtgt.setEnabled(true);
        txtcmnd.setEnabled(true);
        txtngays.setEnabled(true);
        txtdiachi.setEnabled(true);
        txtsdt.setEnabled(true);
        txtemail.setEnabled(true);
        txttaikhoan.setEnabled(true);
        txttienphat.setEnabled(true);
        buttPanexecute.setEnabled(true);
        jComboBox2.setEnabled(false);
        jComboBox3.setEnabled(true);
    }//GEN-LAST:event_buttPanThemMouseClicked

    private void buttPanThemFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttPanThemFileMouseClicked
        // TODO add your handling code here:

        focusThemFile.setOpaque(true);
        focusThemFile.setBackground(Color.red);
        unFocus(new JPanel[]{focusThem, focusSua, focusXoa, focusTK});
        buttPanexecute.setText("");

        disableTextboxes();

        JFileChooser input = new JFileChooser();
        input.setDialogTitle("Tìm file nguồn");
        if (input.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {

            File file = input.getSelectedFile();
            try {
                DocGiaDAO.ThemTuFile(file);
                Load_RefreshTable();
                //SetModelToCombobox();
                JOptionPane.showMessageDialog(null, "Thêm thành công!");
            } catch (ClassNotFoundException | SQLException | IOException ex) {
                JOptionPane.showMessageDialog(null, "Thêm thất bại!");
                Logger.getLogger(testQuanLiDocGia.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttPanThemFileMouseClicked

    private void buttPanSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttPanSuaMouseClicked
        // TODO add your handling code here:

        focusSua.setOpaque(true);
        focusSua.setBackground(Color.red);
        unFocus(new JPanel[]{focusThemFile, focusThem, focusXoa, focusTK});
        CN = 2;
        ExecuteLabel.setText("Sửa");

        txtmadg.setEnabled(true);
        txttendg.setEnabled(true);
        txtgt.setEnabled(true);
        txtcmnd.setEnabled(true);
        txtngays.setEnabled(true);
        txtdiachi.setEnabled(true);
        txtsdt.setEnabled(true);
        txtemail.setEnabled(true);
        txttaikhoan.setEnabled(true);
        txttienphat.setEnabled(true);
        buttPanexecute.setEnabled(true);
        jComboBox2.setEnabled(true);
        jComboBox3.setEnabled(true);
    }//GEN-LAST:event_buttPanSuaMouseClicked

    private void buttPanXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttPanXoaMouseClicked
        // TODO add your handling code here:

        focusXoa.setOpaque(true);
        focusXoa.setBackground(Color.red);
        unFocus(new JPanel[]{focusThemFile, focusSua, focusThem, focusTK});
        CN = 3;
        ExecuteLabel.setText("Xóa");

        txtmadg.setEnabled(true);
        txttendg.setEnabled(false);
        txtgt.setEnabled(false);
        txtcmnd.setEnabled(false);
        txtngays.setEnabled(false);
        txtdiachi.setEnabled(false);
        txtsdt.setEnabled(false);
        txtemail.setEnabled(false);
        txttaikhoan.setEnabled(false);
        txttienphat.setEnabled(false);
        buttPanexecute.setEnabled(true);
        jComboBox2.setEnabled(true);
        jComboBox3.setEnabled(false);
    }//GEN-LAST:event_buttPanXoaMouseClicked

    private void buttPanexecuteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttPanexecuteMouseClicked
        // TODO add your handling code here:

        String strMaDG = txtmadg.getText();
        if (isNull(txtmadg, strMaDG, "Mã độc giả")) {
            return;
        }

        if (CN == 1) {

            // lay thong tin tu text fields
            String strTenDG = txttendg.getText();
            if (isNull(txttendg, strTenDG, "Tên độc giả")) {
                return;
            }

            String strGT = txtgt.getText();

            String strCMND = txtcmnd.getText();
            if (isNull(txtcmnd, strCMND, "Số CMND")) {
                return;
            }
            try {
                Long.parseLong(strCMND);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Giá trị '" + strCMND + "' không hợp lệ!");
                txtcmnd.requestFocus();
                return;
            }

            String strNS = txtngays.getText();
            if (isNull(txtngays, strNS, "Ngày sinh")) {
                return;
            }
            try {
                Date.valueOf(strNS);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Giá trị '" + strNS + "' không hợp lệ!");
                txtngays.requestFocus();
                return;
            }

            String strDC = txtdiachi.getText();
            if (isNull(txtdiachi, strDC, "Địa chỉ")) {
                return;
            }

            String strDT = txtsdt.getText();
            if (isNull(txtsdt, strDT, "Số điện thoại")) {
                return;
            }
            try {
                Long.parseLong(strDT);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Giá trị '" + strDT + "' không hợp lệ!");
                txtsdt.requestFocus();
                return;
            }

            String strEM = txtemail.getText();

            String strTK = txttaikhoan.getText();
            if (isNull(txttaikhoan, strTK, "Số tiền trong tài khoản")) {
                return;
            }

            String strTP = txttienphat.getText();
            if (isNull(txttienphat, strTP, "Tiền phạt")) {
                return;
            }
            try {
                Long.parseLong(strTP);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Giá trị '" + strTP + "' không hợp lệ!");
                txttienphat.requestFocus();
                return;
            }

            if (DocGiaDAO.isIDExistence(strMaDG.trim())) {
                JOptionPane.showMessageDialog(null, "Mã độc giả " + strMaDG.trim() + " đã có trong hệ thống");
                txtmadg.requestFocus();
                return;
            }

            DocGiaDTO newDTO = new DocGiaDTO(strMaDG, strTenDG, strGT, Long.parseLong(strCMND), Date.valueOf(strNS), strDC, Long.parseLong(strDT), strEM, Long.parseLong(strTK), Long.parseLong(strTP));

            try {
                DocGiaDAO.Them(newDTO);
                JOptionPane.showMessageDialog(null, "Thêm thành công!");
                Load_RefreshTable();
                SetModelToCombobox();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(testQuanLiDocGia.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(testQuanLiDocGia.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (CN == 2) {

            // lay thong tin tu text fields
            String strTenDG = txttendg.getText();
            if (isNull(txttendg, strTenDG, "Tên độc giả")) {
                return;
            }

            String strGT = txtgt.getText();

            String strCMND = txtcmnd.getText();
            if (isNull(txtcmnd, strCMND, "Số CMND")) {
                return;
            }
            try {
                Long.parseLong(strCMND);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Giá trị '" + strCMND + "' không hợp lệ!");
                txtcmnd.requestFocus();
                return;
            }

            String strNS = txtngays.getText();
            if (isNull(txtngays, strNS, "Ngày sinh")) {
                return;
            }
            try {
                Date.valueOf(strNS);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Giá trị '" + strNS + "' không hợp lệ!");
                txtngays.requestFocus();
                return;
            }

            String strDC = txtdiachi.getText();
            if (isNull(txtdiachi, strDC, "Địa chỉ")) {
                return;
            }

            String strDT = txtsdt.getText();
            if (isNull(txtsdt, strDT, "Số điện thoại")) {
                return;
            }
            try {
                Long.parseLong(strDT);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Giá trị '" + strDT + "' không hợp lệ!");
                txtsdt.requestFocus();
                return;
            }

            String strEM = txtemail.getText();

            String strTK = txttaikhoan.getText();
            if (isNull(txttaikhoan, strTK, "Số tiền trong tài khoản")) {
                return;
            }

            String strTP = txttienphat.getText();
            if (isNull(txttienphat, strTP, "Tiền phạt")) {
                return;
            }
            try {
                Long.parseLong(strTP);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Giá trị '" + strTP + "' không hợp lệ!");
                txttienphat.requestFocus();
                return;
            }

            if (!DocGiaDAO.isIDExistence(strMaDG.trim())) {
                JOptionPane.showMessageDialog(null, "Mã độc giả " + strMaDG.trim() + " chưa có trong hệ thống");
                txtmadg.requestFocus();
                return;
            }

            DocGiaDTO newDTO = new DocGiaDTO(strMaDG, strTenDG, strGT, Long.parseLong(strCMND), Date.valueOf(strNS), strDC, Long.parseLong(strDT), strEM, Long.parseLong(strTK), Long.parseLong(strTP));

            try {
                DocGiaDAO.ModifyRecord(newDTO);
                JOptionPane.showMessageDialog(null, "Sửa thành công!");
                Load_RefreshTable();
            } catch (SQLException ex) {
                Logger.getLogger(testQuanLiDocGia.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (CN == 3) {

            if (!DocGiaDAO.isIDExistence(strMaDG.trim())) {
                JOptionPane.showMessageDialog(null, "Mã độc giả " + strMaDG.trim() + " chưa có trong hệ thống");
                txtmadg.requestFocus();
                return;
            }

            int choice = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa độc giả có mã " + txtmadg.getText() + "?", "Confirm", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                DocGiaDAO.DeleteReCord(txtmadg.getText());
                JOptionPane.showMessageDialog(null, "Xoá thành công!");
                Load_RefreshTable();
                SetModelToCombobox();
            }
        }
    }//GEN-LAST:event_buttPanexecuteMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Menu CNFrame = new Menu();
        CNFrame.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void buttPanTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttPanTKMouseClicked
        // TODO add your handling code here:
        focusTK.setOpaque(true);
        focusTK.setBackground(Color.red);
        unFocus(new JPanel[]{focusThemFile, focusSua, focusXoa, focusThem});
        ExecuteLabel.setText("");

        disableTextboxes();

        GUIThongKeDG.main(null);
    }//GEN-LAST:event_buttPanTKMouseClicked

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        txtmadg.setText(jComboBox2.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // TODO add your handling code here:
        txtgt.setText(jComboBox3.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void TieuChiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TieuChiItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {

            if (TieuChi.getSelectedItem().equals("Mã độc giả")) {
                TieuChiTK = "MA_DOC_GIA";
            } else if (TieuChi.getSelectedItem().equals("Tên độc giả")) {
                TieuChiTK = "TEN_DOC_GIA";
            } else if (TieuChi.getSelectedItem().equals("Giới tính")) {
                TieuChiTK = "GIOI_TINH";
            } else if (TieuChi.getSelectedItem().equals("CMND")) {
                TieuChiTK = "CMND";
            } else if (TieuChi.getSelectedItem().equals("Ngày sinh")) {
                TieuChiTK = "NGAY_SINH";
            } else if (TieuChi.getSelectedItem().equals("Địa chỉ")) {
                TieuChiTK = "DIA_CHI";
            } else if (TieuChi.getSelectedItem().equals("Số điện thoại")) {
                TieuChiTK = "SO_DIEN_THOAI";
            } else if (TieuChi.getSelectedItem().equals("Email")) {
                TieuChiTK = "EMAIL";
            } else if (TieuChi.getSelectedItem().equals("Tài khoản")) {
                TieuChiTK = "TAI_KHOAN";
            } else if (TieuChi.getSelectedItem().equals("Tiền phạt")) {
                TieuChiTK = "TIEN_PHAT";
            } else {
                TieuChiTK = "ALL";
            }
        }
    }//GEN-LAST:event_TieuChiItemStateChanged

    private void buttXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttXuatFileActionPerformed
        // TODO add your handling code here:
        TableModel model = tableDG.getModel();// TableModel implementation here
        JTable table = new JTable(model);
        
        Map params = new HashMap();
        
        JRDataSource dataSource = new JRTableModelDataSource(table.getModel());
        JasperPrint print;
        try {
            print = JasperFillManager.fillReport("E:\\", params, dataSource);
            JasperViewer.viewReport(print, true); // true == Exit on Close
        } catch (JRException ex) {
            Logger.getLogger(testQuanLiDocGia.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buttXuatFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testQuanLiDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testQuanLiDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testQuanLiDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testQuanLiDocGia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testQuanLiDocGia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExecuteLabel;
    private javax.swing.JTextField SearchingContent;
    private javax.swing.JComboBox<String> TieuChi;
    private javax.swing.JPanel buttPanSua;
    private javax.swing.JPanel buttPanTK;
    private javax.swing.JPanel buttPanThem;
    private javax.swing.JPanel buttPanThemFile;
    private javax.swing.JPanel buttPanXoa;
    private javax.swing.JLabel buttPanexecute;
    private javax.swing.JButton buttXuatFile;
    private javax.swing.JPanel focusSua;
    private javax.swing.JPanel focusTK;
    private javax.swing.JPanel focusThem;
    private javax.swing.JPanel focusThemFile;
    private javax.swing.JPanel focusXoa;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableDG;
    private javax.swing.JTextField txtcmnd;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtgt;
    private javax.swing.JTextField txtmadg;
    private javax.swing.JTextField txtngays;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txttaikhoan;
    private javax.swing.JTextField txttendg;
    private javax.swing.JTextField txttienphat;
    // End of variables declaration//GEN-END:variables
}
